name: chat-alpha-chat

services:
  scylla:
    image: scylladb/scylla:5.4
    container_name: chat-alpha-scylla
    restart: unless-stopped
    ports:
      - "9042:9042"
    command: --smp 1 --memory 750M --overprovisioned 1
    networks:
      - chat-alpha-network
    volumes:
      - scylladata:/var/lib/scylla

volumes:
  scylladata:

networks:
  chat-alpha-network:
    external: true